# Generated by Django 4.2.6 on 2024-01-03 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.CharField(blank=True, default='', max_length=1000, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Auction Price')),
                ('listedat', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Listed At')),
                ('isactive', models.BooleanField(default=True, verbose_name='Auction Status')),
                ('bid', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Bid Price')),
                ('bidder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='BidWinnerList', to=settings.AUTH_USER_MODEL, verbose_name='Bidder')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Category Name')),
            ],
        ),
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auctionid', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='AuctionListWatchList', to='auctions.auctionlist')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='UserWatchList', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidprice', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Bid Price')),
                ('auctionid', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='AuctionListBidList', to='auctions.auctionlist')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='UserBidList', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='auctionlist',
            name='categoryid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='CategoryAuctionList', to='auctions.category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='auctionlist',
            name='listedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='UserAuctionList', to=settings.AUTH_USER_MODEL, verbose_name='Listed By'),
        ),
        migrations.CreateModel(
            name='AuctionComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=1000)),
                ('postedat', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Posted At')),
                ('auctionid', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='AuctionListCommentList', to='auctions.auctionlist')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='UserAuctionCommentList', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
